---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Time Series Forecasting: Machine Learning and Deep Learning with R & Python

*Overview*

In the last 15 years, business requests related to time series forecasting changed 
dramatically. Business needs evolved from predicting at most 100, low frequency data, 
to forecasting 10.000, high frequency time series. Unfortunately, the classical 
tools may not be the best anymore, both in terms of accuracy and computationally. 
Hence, nowadays the “time series forecasting” data scientist is required to be 
capable of providing business forecasting solutions tackling both scalability and 
accuracy, constantly keeping up-to-date with new methods.

The aim of the course is to teach how time series forecasting problems can be 
solved in practice. The state-of-the-art techniques are presented from a very 
practical point of view, throughout **R** tutorials. **Python** algorithms are also 
presented and used within R by means of the reticulate package.  


## General Information

- [Course Descriprion (for Students)](https://marcozanotti.github.io/tsforecasting-course/general-infos/tsf_description.html)  
- [Course Descriprion (for Business Experts)](https://marcozanotti.github.io/tsforecasting-course/general-infos/tsf_description_business.html)  
- [Syllabus](https://marcozanotti.github.io/tsforecasting-course/general-infos/tsf_syllabus.html)  

  
## Materials

- [Presentation](https://marcozanotti.github.io/tsforecasting-course/resources/presentation/tsfor_presentation.html)  
- [Tutorials (lectures)](https://github.com/marcozanotti/tsforecasting-course/tree/master/R)   
- [Data](https://marcozanotti.github.io/tsforecasting-course/R/tsfor_lecture0_data.html)  


## Challenges

- [Jumpstart](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge0_jumpstart.html)  
- [Feature Engineering](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge1_feateng.html)  
- [New Algos](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge2_newalgos.html)  
- [Tuning](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge3_tuning.html)  
- [Testing Algos](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge4_algos.html)  
- [Modeltime (optional)](https://marcozanotti.github.io/tsforecasting-course/challenges/tsfor_challenge_optional_modeltime.html)  


## Hackathon

- [Hackathon: M4 Competition](https://marcozanotti.github.io/tsforecasting-course/exam/tsf_hackaton1.html) 
- [Hackathon: Wind Forecast](https://marcozanotti.github.io/tsforecasting-course/exam/tsf_hackaton2.html) 

