---
title: "Time Series Forecasting Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: css/styles-default.css
    logo: img/logo.png
runtime: shiny
---

```{r setup, include=FALSE, message=FALSE}
source("R/utils.R")
source("R/packages.R")
```

```{r auth}
# credentials <- read.csv("auth.txt")
# shinymanager::auth_ui(id = "auth")
# auth <- shiny::callModule(
#   module = shinymanager::auth_server,
#   id = "auth",
#   check_credentials = shinymanager::check_credentials(credentials)
# )
```

```{r data}
data1 <- tibble(
  date = seq.Date(from = as.Date("2010-01-01"), to = as.Date("2023-12-31"), by = "day"),
  id = "TS 1 - daily",
  value = rnorm(n = 5113, mean = 100, sd = 1000) + 1:5113 + sin(365)
)

data2 <- tibble(
  date = seq.Date(from = as.Date("2010-01-01"), to = as.Date("2023-12-31"), by = "week"),
  id = "TS 2 - weekly",
  value = rnorm(n = 731, mean = 100, sd = 1000) + 1:731 + sin(52)
)

data3 <- tibble(
  date = seq.Date(from = as.Date("2010-01-01"), to = as.Date("2023-12-31"), by = "month"),
  id = "TS 3 - monthly",
  value = rnorm(n = 168, mean = 100, sd = 1000) + 1:168 + sin(6)
)

data4 <- tibble(
  date = seq.Date(from = as.Date("2010-01-01"), to = as.Date("2023-12-31"), by = "quarter"),
  id = "TS 4 - quarterly",
  value = rnorm(n = 56, mean = 100, sd = 1000) + 1:56 + sin(2)
)

data5 <- tibble(
  date = seq.Date(from = as.Date("2010-01-01"), to = as.Date("2023-12-31"), by = "year"),
  id = "TS 5 - yearly",
  value = rnorm(n = 14, mean = 100, sd = 1000) + 1:14
)

data <- bind_rows(data1, data2, data3, data4, data5)

fcst_methods <- c("Rolling Average", "ETS", "ARIMA", "SARIMA", "TBATS", "STLM", "Linear Regression", "Elastic Net")
# ("PROPHET", "NAIVE", "SNAIVE", "RWDRIFT", "RWF", "CROSTON", 
# "NNETAR", "STL", "VAR", "LR", "ANN", "MLP", "RNN", "LSTM", "GRU", 
# "BAGGED", "RF", "XGBOOST", "SVM", "KNN", "DLM", "DAMPED", "THETA", 
# "BU", "MINM")
```



Sidebar {.sidebar}
---------------------------------------------------------------

```{r}
useShinyjs(rmd = TRUE) # use Shiny JavaScript to allow delay on buttons

br() # break rule

shinyWidgets::dropdownButton(
  tags$h3("List of Input"),
  selectInput(inputId = "ts_id", label = "Time Series", choices = unique(data$id), selected = unique(data$id)[3]),
  # dateRangeInput(inputId = "date_range", label = "Date Range", start = min(data$date), end = max(data$date), min = min(data$date), max = max(data$date)),
  numericInput(inputId = "n_future", label = "Forecast Horizon", value = 12, min = 1),
  circle = TRUE,
  status = "primary", 
  size = "sm",
  icon = icon("gear"), width = "300px",
  tooltip = tooltipOptions(title = "Click to see inputs!")
)

br() # break rule

selectInput(inputId = "method", label = h3("Forecast Method"), choices = fcst_methods, selected = fcst_methods[1])

# ARIMA
conditionalPanel(
  condition = "input.method == 'Rolling Average'",
  h5("Method hyperparameters: "),
  numericInput(inputId = "window_size", label = "Window Size", value = 12, min = 1)
)

# ETS
conditionalPanel(
  condition = "input.method == 'ETS'",
  h5("Method hyperparameters: "),
  selectInput(inputId = "error", label = "Error", choices = c("auto", "additive", "multiplicative"), selected = "auto"),
  selectInput(inputId = "trend", label = "Trend", choices = c("auto", "additive", "multiplicative", "none"), selected = "auto"),
  selectInput(inputId = "season", label = "Seasonality", choices = c("auto", "additive", "multiplicative", "none"), selected = "auto"),
  selectInput(inputId = "damping", label = "Damped Trend", choices = c("auto", "damped", "none"), selected = "auto"),
  numericInput(inputId = "smooth_level", label = "Alpha", value = 0.1, min = 0, max = 1),
  numericInput(inputId = "smooth_trend", label = "Beta", value = 0.1, min = 0, max = 1),
  numericInput(inputId = "smooth_season", label = "Gamma", value = 0.1, min = 0, max = 1)
)

# ARIMA
conditionalPanel(
  condition = "input.method == 'ARIMA'",
  h5("Method hyperparameters: "),
)

# Linear Regression
conditionalPanel(
  condition = "input.method == 'Linear Regression'",
  h5("Method hyperparameters: "),
  h6("No hyperparameters for this method!")
)

br() # break rule

actionButton(inputId = "apply_forecast", label = "Forecast!", icon = icon("play"))

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))
observeEvent(
  eventExpr = input$reset, 
  handlerExpr = {
    updateSelectInput(session = session, inputId = "ts_id", selected = unique(data$id)[3])
    updateNumericInput(session = session, inputId = "n_future", value = 12)
    updateSelectInput(session = session, inputId = "method", selected = fcst_methods[1])
    shinyjs::delay(ms = 300, expr = {shinyjs::click(id = "apply")})
  }
)

# input <- list(
#   ts_id = unique(data$id)[3],
#   n_future = 12,
#   method = "ETS",
#   error = "auto",
#   trend = "auto",
#   season = "auto",
#   damping = "auto",
#   smooth_level = 0.1,
#   smooth_trend = 0.1,
#   smooth_season = 0.1
# )
```

```{r}
data_filtered <- reactive({
  # data_filtered <- 
  data |>
    filter(id %in% input$ts_id)
    # filter(between(date, input$date_range_1[1], input$date_range_1[2]))
})
```



Row {data-height=700}
---------------------------------------------------------------

### Forecasting Plot

```{r}
forecast_results <- eventReactive(
  eventExpr = input$apply_forecast,
  valueExpr = {
    # data_pred <-
    data_filtered() |>
    generate_forecast(
      method = input$method, 
      params = input,
      n_future = input$n_future, 
      seed = 1992
    )
  }
)
```

```{r}
output$plotly_ts <- renderPlotly({
  
  p <- data_filtered() |> 
      timetk::plot_time_series(
        .date_var = date, .value = value, 
        .interactive = TRUE, .smooth = FALSE
      )
  if (input$apply_forecast) {
    p <- forecast_results()$forecast |> 
      modeltime::plot_modeltime_forecast(.legend_show = FALSE)
  }
  
})
plotlyOutput(outputId = "plotly_ts")
```


Row {data-height=300}
---------------------------------------------------------------

### Model Summary

```{r}
output$model_summary <- renderPrint({
  
  "No model applied yet!"
  if (input$apply_forecast) {
    forecast_results()$model
  } 
  
})
verbatimTextOutput(outputId = "model_summary")
```

