---
title: "| Time Series Forecasting:  \n| Machine Learning and Deep Learning with R
  and Python\n- Course Syllabus -"
author: "Marco Zanotti"
date: ""
output:
  pdf_document: default
  rmdformats::downcute:
    highlight: tango
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Lecture 1: Time Series Manipulations, Transformations & Visualizations

**Manipulations**:  
- summarizing by time  
- padding by time  
- filtering by time  
- mutating by time  
- joining by time  

**Transformations**:   
- variance reduction  
- range reduction  
- smoothing  
- rolling averages  
- missing values imputation  
- anomaly detection and cleaning  
- lags and differencing  
- Fourier transforms  
- confined intervals  

**Visualizations**:  
- time series  
- autocorrelations  
- cross-correlations  
- smoothing  
- seasonality  
- time series decomposition  
- anomaly detection  
- time series regressions  


## Lecture 2: Time Series Features Engineering

**Feature Engineering**:  
- time-based features  
- trend-based features  
- seasonal features  
- interaction features  
- rolling average features  
- lag features  
- Fourier features  
- event data features  
- external features  

**Tidymodel**:  
- recipes  
- workflows  


## Lecture 3: Tidymodel & Modeltime

**Tidymodel**:  
- package framework  

**Modeltime**:  
- package framework  
- algorithm specifications  
- workflows  
- calibration  
- evaluation  
- refitting  
- forecasting  


## Lecture 4: Time Series Models

**Forecasting Methods**:  
- Naive / Seasonal Naive  
- Window Functions  
- S-ARIMA-X  
- Exponential Smoothing  
- TBATS  
- STLM (Decomposition models)  
- Facebook's Prophet  


## Lecture 5: Machine Learning Models

**Forecasting Methods**:  
- Linear Regression  
- Elastic Net  
- MARS  
- SVM  
- KNN  
- Random Forest  
- Boosting  
- Cubist  
- Neural Network  


## Lecture 6: Boosting Time Series Models

**Forecasting Methods**:  
- ARIMA Boost  
- Prophet Boost  


## Lecture 7: Deep Learning Models

**Forecasting Methods**:    
- GluonTS Deep AR   
- GluonTS NBEATS    
- GluonTS GP Forecaster  
- GluonTS Deep State  
- Torch Deep AR   


## Lecture 8: Automatic Machine Learning

**Forecasting Methods**:  
- H2O  


<!--
### Lecture 9: Bayesian Modelling

**Forecasting Methods**:  
- 


### Lecture 10: GAMs Modelling

**Forecasting Methods**:  
- 
-->


## Lecture 9: Hyperparameter Tuning

**Methods**:    
- Sequential  
- Non-Sequential  

**Cross Validation**:  
- Time Series Cross Validation  
- V-Fold Cross Validation  
- Grid Searches  


## Lecture 10: Ensemble Learning

**Forecasting Methods**:  
- Simple Averaging Ensemble  
- Weight Averaging Ensemble  
- Stacking and Metalearning  
- Multi-level Ensemble  


## Lecture 11: Recursive Machine Learning Forecasting

**ML Recursivity**:  
- single time series recursive modelling  
- panel data recursive modelling


### Lecture 12: Panel Data Forecasting

**Forecasting Methods**:  
- Nested Forecasting  
- Global Modelling  
<!--- Hierarchical Time Series Forecasting-->


<!--
### Lecture 13: Spark Backend

**Sparlyr**:  
- single time series Spark workflow
- panel data Spark workflow
-->

