---
title: "Time Series Forecasting with Machine Learning & Deep Learning\n"
author: "Marco Zanotti"
date: ""
output:
  pdf_document: default
  rmdformats::downcute:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;  

## Introduction

In the last 15 years, business requests related to time series forecasting
changed dramatically. Business needs evolved from predicting at most
100, low frequency (mainly monthly or quarterly) data, to forecasting 
10.000, high frequency (mainly daily data) time series. 
Unfortunately, the classical tools that were highly used in the past years 
may not be the best anymore, both in terms of accuracy and computationally.  
Moreover, the review of M-Series Forecasting Competitions suggests that 
newer ML and DL models, or stacking ensemble techniques may be very accurate 
compared to easier solutions. 

For these reasons, nowadays the "time series forecasting" data scientist
is required to be capable of providing business forecasting solutions
tackling both scalability and accuracy, constantly keeping up-to-date
with new methods.  


## Course Structure

The aim of the course is to teach the students how time series 
forecasting problems can be solved in practice.  
The state-of-the-art techniques are presented from a very practical 
point of view, throughout R tutorials on each main topic. 
Python algorithms are also presented and used within R by means 
of the *reticulate* package.
Theoretical concepts are left to those who are interested in and 
bibliographic references are listed at the end of the course.


## Contents

* Time Series Manipulations, Transformations & Visualizations
* Time Series Features Engineering
* Time Series Models
* Machine Learning Models
* Deep Learning Models
* Automatic Machine Learning
* Hyperparameter Tuning
* Ensemble Learning
* Recursivity of ML Models
* Nested (Iterative) Forecasting
* Global Modelling

Specific business needs may be discussed during the lectures.  


## Duration

The course has a duration of 20 hours.  


## Beneficiaries

This course is intended for data scientist, data analyst, 
statisticians, IT specialists, developers, project managers and 
business leaders who want to develop the most in-demand skills to  
solve time series forecasting problems.   


## Requirements

Basic statistic and programming knowledge.
